package com.glodon.data_view.dao.model;

public class DataScreenWithBLOBs extends DataScreen {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_screen.opt
     *
     * @mbg.generated Thu Nov 14 20:26:50 CST 2019
     */
    private String opt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_screen.layout
     *
     * @mbg.generated Thu Nov 14 20:26:50 CST 2019
     */
    private String layout;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_screen.opt
     *
     * @return the value of data_screen.opt
     *
     * @mbg.generated Thu Nov 14 20:26:50 CST 2019
     */
    public String getOpt() {
        return opt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_screen.opt
     *
     * @param opt the value for data_screen.opt
     *
     * @mbg.generated Thu Nov 14 20:26:50 CST 2019
     */
    public void setOpt(String opt) {
        this.opt = opt == null ? null : opt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_screen.layout
     *
     * @return the value of data_screen.layout
     *
     * @mbg.generated Thu Nov 14 20:26:50 CST 2019
     */
    public String getLayout() {
        return layout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_screen.layout
     *
     * @param layout the value for data_screen.layout
     *
     * @mbg.generated Thu Nov 14 20:26:50 CST 2019
     */
    public void setLayout(String layout) {
        this.layout = layout == null ? null : layout.trim();
    }
}