package com.glodon.data_view.dao.model;

import java.io.Serializable;
import java.util.Date;

public class Project implements Serializable {

    private static final long serialVersionUID = 4278721827560421125L;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column project.id
     *
     * @mbg.generated Sun Nov 10 13:51:31 CST 2019
     */
    private Integer           id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column project.name
     *
     * @mbg.generated Sun Nov 10 13:51:31 CST 2019
     */
    private String            name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column project.published
     *
     * @mbg.generated Sun Nov 10 13:51:31 CST 2019
     */
    private Boolean           published;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column project.user_id
     *
     * @mbg.generated Sun Nov 10 13:51:31 CST 2019
     */
    private Integer           userId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column project.create_time
     *
     * @mbg.generated Sun Nov 10 13:51:31 CST 2019
     */
    private Date              createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column project.update_time
     *
     * @mbg.generated Sun Nov 10 13:51:31 CST 2019
     */
    private Date              updateTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column project.id
     *
     * @return the value of project.id
     * @mbg.generated Sun Nov 10 13:51:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     * @mbg.generated Sun Nov 10 13:51:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column project.name
     *
     * @return the value of project.name
     * @mbg.generated Sun Nov 10 13:51:31 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column project.name
     *
     * @param name the value for project.name
     * @mbg.generated Sun Nov 10 13:51:31 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * project.published
     *
     * @return the value of project.published
     * @mbg.generated Sun Nov 10 13:51:31 CST 2019
     */
    public Boolean getPublished() {
        return published;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * project.published
     *
     * @param published the value for project.published
     * @mbg.generated Sun Nov 10 13:51:31 CST 2019
     */
    public void setPublished(Boolean published) {
        this.published = published;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * project.user_id
     *
     * @return the value of project.user_id
     * @mbg.generated Sun Nov 10 13:51:31 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column project.user_id
     *
     * @param userId the value for project.user_id
     * @mbg.generated Sun Nov 10 13:51:31 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * project.create_time
     *
     * @return the value of project.create_time
     * @mbg.generated Sun Nov 10 13:51:31 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * project.create_time
     *
     * @param createTime the value for project.create_time
     * @mbg.generated Sun Nov 10 13:51:31 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * project.update_time
     *
     * @return the value of project.update_time
     * @mbg.generated Sun Nov 10 13:51:31 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * project.update_time
     *
     * @param updateTime the value for project.update_time
     * @mbg.generated Sun Nov 10 13:51:31 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}
