package com.glodon.data_view.dao.mapper;

import com.glodon.data_view.dao.model.DataScreen;
import com.glodon.data_view.dao.model.DataScreenWithBLOBs;

import java.util.List;
import java.util.Map;

public interface DataScreenMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table data_screen
     *
     * @mbg.generated Thu Nov 14 20:26:50 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table data_screen
     *
     * @mbg.generated Thu Nov 14 20:26:50 CST 2019
     */
    int insert(DataScreenWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table data_screen
     *
     * @mbg.generated Thu Nov 14 20:26:50 CST 2019
     */
    int insertSelective(DataScreenWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table data_screen
     *
     * @mbg.generated Thu Nov 14 20:26:50 CST 2019
     */
    DataScreenWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table data_screen
     *
     * @mbg.generated Thu Nov 14 20:26:50 CST 2019
     */
    int updateByPrimaryKeySelective(DataScreenWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table data_screen
     *
     * @mbg.generated Thu Nov 14 20:26:50 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(DataScreenWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table data_screen
     *
     * @mbg.generated Thu Nov 14 20:26:50 CST 2019
     */
    int updateByPrimaryKey(DataScreen record);

    int countByCondition(Map<String, Object> condition);

    List<DataScreenWithBLOBs> selectByCondition(Map<String, Object> condition);

    DataScreenWithBLOBs selectTopOneByCreateTime();

    void deleteByProjectId(Integer projectId);
}
